from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import ItemClassification, Location

from . import items

if TYPE_CHECKING:
    from .world import MLDTWorld

# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.
LOCATION_NAME_TO_ID = {
    "Bp West of Pi'illo Castle Block": 1,
    "Bp Toad Crash Room Block 1": 2,
    "Bp Toad Crash Room Block 2": 3,
    "Bp Toad Crash Room Block 3": 4,
    "Bp Toad Crash Room Block 4": 5,
    "Bp Second Toad Crash Room Block 1": 6,
    "Bp Second Toad Crash Room Block 2": 7,
    "Bp Second Toad Crash Room Block 3": 8,
    "Bp Second Toad Crash Room Block 4": 9,
    "Bp East of Pi'illo Castle Block": 10,
    "Bp Behind Pi'illo Castle Block": 11,
    "Bp West of Pi'illo Castle Bean Spot": 12,
    "Bp East of Pi'illo Castle Bean Spot": 13,
    "Bp Behind Pi'illo Castle Bean Spot 1": 14,
    "Bp Behind Pi'illo Castle Bean Spot 2": 15,
    "Bp Behind Pi'illo Castle Bean Spot 3": 16,
    "Bp Behind Pi'illo Castle Bean Spot 4": 17,
    "PiC Staff Break Room Block 1": 101,
    "PiC Staff Break Room Block 2": 102,
    "PiC Hotel Entrance Block 1": 103,
    "PiC Hotel Entrance Block 2": 104,
    "PiC Hotel Lobby Block": 105,
    "PiC Hotel Left Room Block": 106,
    "PiC Hotel Topright Room Block": 107,
    "PiC Ball Hop Room Entrance Block 1": 108,
    "PiC Ball Hop Room Entrance Block 2": 109,
    "PiC Stairs to Smoldergeist Block": 110,
    "PiC Restaurant District Block": 111,
    "PiC Hotel Balcony Block": 112,
    "DPiC Door Tutorial Room Block": 113,
    "DPiC Many Door Room Block 1": 114,
    "DPiC Many Door Room Block 2": 115,
    "DPiC Many Enemy Room Block 1": 116,
    "DPiC Many Enemy Room Block 2": 117,
    "DPiC Many Enemy Room Block 3": 118,
    "DPiC Many Enemy Room Block 4": 119,
    "DPiC Many Enemy Room Block 5": 120,
    "PiC Ball Hop Room Block 1": 121,
    "PiC Ball Hop Room Block 2": 122,
    "PiC Ball Hop Room Block 3": 123,
    "PiC Ball Hop Room Block 4": 124,
    "PiC Ball Hop Room Block 5": 125,
    "PiC Deep Pi'illo Castle Block Room Block 1": 126,
    "PiC Deep Pi'illo Castle Block Room Block 2": 127,
    "PiC Deep Pi'illo Castle Block Room Block 3": 128,
    "PiC Deep Pi'illo Castle Block Room Block 4": 129,
    "DPiC Learn Luiginary Ball Room Block": 201,
    "DPiC Learn Luiginary Hookshot Room Block": 202,
    "DPiC Dream's Deep Room 5 Block 1": 203,
    "DPiC Dream's Deep Room 5 Block 2": 204,
    "DPiC Learn Luiginary Ball Hammer Room Block": 205,
    "DPiC First Throw Pi'illo Room 2 Block": 301,
    "DPiC First Throw Pi'illo Room 3 Block 1": 302,
    "DPiC First Throw Pi'illo Room 3 Block 2": 303,
    "DPiC First Throw Pi'illo Room 3 Block 3": 304,
    "DPiC First Throw Pi'illo Room 3 Block 4": 305,
    "DPiC First Throw Pi'illo Room 3 Block 5": 306,
    "DPiC First Throw Pi'illo Room 3 Block 6": 307,
    "DPiC First Throw Pi'illo Room 3 Block 7": 308,
    "DPiC Second Throw Pi'illo Room 2 Block 1": 309,
    "DPiC Second Throw Pi'illo Room 2 Block 2": 310,
    "DPiC Second Throw Pi'illo Room 3 Block 1": 311,
    "DPiC Second Throw Pi'illo Room 3 Block 2": 312,
    "DPiC Second Throw Pi'illo Room 3 Block 3": 313,
    "DPiC Second Throw Pi'illo Room 3 Block 4": 314,
    "DPiC Second Throw Pi'illo Room 3 Block 5": 315,
    "DPiC Second Throw Pi'illo Room 3 Block 6": 316,
    "DPiC Second Throw Pi'illo Room 3 Block 7": 317,
    "DPiC Second Throw Pi'illo Room 3 Block 8": 318,
    "DPiC Second Throw Pi'illo Room 3 Block 9": 319,
    "DPiC Second Throw Pi'illo Room 3 Block 10": 320,
    "DPiC Second Throw Pi'illo Room 3 Block 11": 321,
    "DPiC Second Throw Pi'illo Room 3 Block 12": 322,
    "DPiC Second Throw Pi'illo Room 3 Block 13": 323,
    "DPiC Second Throw Pi'illo Room 3 Block 14": 324,
    "DPiC Second Throw Pi'illo Room 3 Block 15": 325,
    "DPiC Second Throw Pi'illo Room 3 Block 16": 326,
    "DPiC Second Throw Pi'illo Room 3 Block 17": 327,
    "DPiC Second Throw Pi'illo Room 3 Block 18": 328,
    "DPiC Second Throw Pi'illo Room 3 Block 19": 329,
    "DPiC Second Throw Pi'illo Room 3 Block 20": 330,
    "DPiC Second Throw Pi'illo Room 3 Block 21": 331,
    "DPiC Second Throw Pi'illo Room 3 Block 22": 332,
    "DPiC Second Throw Pi'illo Room 3 Block 23": 333,
    "DPiC Second Throw Pi'illo Room 3 Block 24": 334,
    "DPiC Second Throw Pi'illo Room 3 Block 25": 335,
    "DPiC First Pi'illo Room 1 Block": 336,
    "DPiC First Pi'illo Room 2 Block 1": 337,
    "DPiC First Pi'illo Room 2 Block 2": 338,
    "DPiC First Pi'illo Room 2 Block 3": 339,
    "DPiC First Pi'illo Room 2 Block 4": 340,
    "DPiC First Pi'illo Room 3 Block 1": 341,
    "DPiC First Pi'illo Room 3 Block 2": 342,
    "PiC Under Blimport Bridge Falling Point Block": 343,
    "PiC Under Blimport Bridge First Pi'illo Room Block 1": 344,
    "PiC Under Blimport Bridge First Pi'illo Room Block 2": 345,
    "PiC Under Blimport Bridge Second Fling Pi'illo Room Block 1": 346,
    "PiC Under Blimport Bridge Second Fling Pi'illo Room Block 2": 347,
    "PiC Under Blimport Bridge Second Fling Pi'illo Room Block 3": 348,
    "PiC Under Blimport Bridge Second Fling Pi'illo Room Block 4": 349,
    "MrP Entrance Block 1": 401,
    "MrP Entrance Block 2": 402,
    "MrP Hammer Tutorial Room Block 1": 403,
    "MrP Hammer Tutorial Room Block 2": 404,
    "MrP Hammer Tutorial Room Block 3": 405,
    "MrP Hammer Tutorial Room Block 4": 406,
    "MrP Hammer Tutorial Room Block 5": 407,
    "MrP Hammer Tutorial Room Block 6": 408,
    "MrP Gate Room Block 1": 409,
    "MrP Gate Room Block 2": 410,
    "MrP Gate Room Block 3": 411,
    "MrP Fountain Room Block 1": 412,
    "MrP Fountain Room Block 2": 413,
    "MrP Fountain Room Block 3": 414,
    "MrP Fountain Room Block 4": 415,
    "MrP Lower Rock Room Block 1": 416,
    "MrP Lower Rock Room Block 2": 417,
    "MrP Lower Rock Room Block 3": 418,
    "MrP Lower Rock Room Block 4": 419,
    "MrP Maintenance Hut Block 1": 420,
    "MrP Maintenance Hut Block 2": 421,
    "MrP Maintenance Hut Block 3": 422,
    "MrP Maintenance Hut Block 4": 423,
    "MrP Maintenance Hut Block 5": 424,
    "DMrP Eldream Room 2 Block": 425,
    "DMrP Eldream Room 3 Block 1": 426,
    "DMrP Eldream Room 3 Block 2": 427,
    "DMrP Eldream Room 3 Block 3": 428,
    "DMrP Eldream Room 3 Block 4": 429,
    "DMrP Eldream Room 3 Block 5": 430,
    "DMrP Eldream Room 4 Block 1": 431,
    "DMrP Eldream Room 4 Block 2": 432,
    "DMrP Eldream Room 4 Block 3": 433,
    "DMrP Eldream Room 5 Block 1": 434,
    "DMrP Eldream Room 5 Block 2": 435,
    "DMrP Eldream Item Detour Block 1": 436,
    "DMrP Eldream Item Detour Block 2": 437,
    "DMrP Eldream Fountain Room Block": 438,
    "DMrP Eldream Room 7 Block": 439,
    "DMrP Eldream Pipe To Sewers Block": 440,
    "DMrP Eldream Sewers Block 1": 441,
    "DMrP Eldream Sewers Block 2": 442,
    "DMrP Eldream Sewers Block 3": 443,
    "DMrP Eldream Sewers Block 4": 444,
    "DMrP Eldream Throw Boss Brickle Block": 445,
    "DMrP Eldream Buildup to Final Attack Piece Block 1": 446,
    "DMrP Eldream Buildup to Final Attack Piece Block 2": 447,
    "DMrP Eldream Luiginary Attack Tutorial Room Block": 448,
    "DMrP Pi'illo to Hammers Block": 449,
    "DMrP Eldream Clouds 1 Block 1": 450,
    "DMrP Eldream Clouds 1 Block 2": 451,
    "DMrP Eldream Clouds 2 Block": 452,
    "MrP In Front of Wakeport Block": 453,
    "DMrP Eldream Path to Clouds Block": 454,
    "MrP Path to Wakeport Block 1": 455,
    "MrP Path to Wakeport Block 2": 456,
    "MrP Path to Wakeport Block 3": 457,
    "MrP Path to Wakeport Block 4": 458,
    "MrP Somnom Woods Stairs Block": 459,
    "MrP Path to Somnom and Neo Bowser Block": 460,
    "MrP Hammer Tutorial Room Bean Spot 1": 461,
    "MrP Hammer Tutorial Room Bean Spot 2": 462,
    "MrP Hammer Tutorial Room Bean Spot 3": 463,
    "MrP Hammer Tutorial Room Bean Spot 4": 464,
    "MrP Gate Room Bean Spot 1": 465,
    "MrP Gate Room Bean Spot 2": 466,
    "MrP Gate Room Bean Spot 3": 467,
    "MrP Fountain Room Bean Spot 1": 468,
    "MrP Fountain Room Bean Spot 2": 469,
    "MrP Fountain Room Bean Spot 3": 470,
    "MrP Fountain Room Bean Spot 4": 471,
    "MrP Lower Rock Room Bean Spot": 472,
    "MrP Maintenance Hut Bean Spot 1": 473,
    "MrP Maintenance Hut Bean Spot 2": 474,
    "MrP Maintenance Hut Bean Spot 3": 475,
    "MrP Maintenance Hut Bean Spot 4": 476,
    "MrP In Front of Wakeport Bean Spot 1": 477,
    "MrP In Front of Wakeport Bean Spot 2": 478,
    "MrP Path to Wakeport Bean Spot": 479,
    "MrP Somnom Woods Stairs Bean Spot": 480,
    "MrP Path to Somnom and Neo Bowser Bean Spot": 481,
    "MrP West of Hammer Tutorial Room Block 1": 501,
    "MrP West of Hammer Tutorial Room Block 2": 502,
    "MrP River Rocks Block 1": 503,
    "MrP River Rocks Block 2": 504,
    "MrP Upper Attack Piece Room Block 1": 505,
    "MrP Upper Attack Piece Room Block 2": 506,
    "MrP Upper Attack Piece Room Block 3": 507,
    "MrP Upper Attack Piece Room Block 4": 508,
    "MrP Upper Attack Piece Room Block 5": 509,
    "MrP Lower Attack Piece Room Block 1": 510,
    "MrP Lower Attack Piece Room Block 2": 511,
    "MrP Lower Attack Piece Room Block 3": 512,
    "MrP Lower Attack Piece Room Block 4": 513,
    "MrP Lower Attack Piece Room Block 5": 514,
    "MrP Lower Attack Piece Room Block 6": 515,
    "MrP Lower Attack Piece Room Block 7": 516,
    "MrP Lower Attack Piece Room Block 8": 517,
    "MrP East of Hammer Tutorial Room Block 1": 518,
    "MrP East of Hammer Tutorial Room Block 2": 519,
    "MrP Upper Rock Room Block 1": 520,
    "MrP Upper Rock Room Block 2": 521,
    "MrP Upper Rock Room Block 3": 522,
    "MrP Upper Rock Room Block 4": 523,
    "MrP Upper Rock Room Block 5": 524,
    "MrP Upper Rock Room Block 6": 525,
    "MrP Many Enemy Room Block 1": 526,
    "MrP Many Enemy Room Block 2": 527,
    "MrP Many Enemy Room Block 3": 528,
    "MrP Underground Block 1": 529,
    "MrP Underground Block 2": 530,
    "MrP Upper Attack Piece Room Bean Spot": 531,
    "MrP Upper Rock Room Bean Spot 1": 532,
    "MrP Upper Rock Room Bean Spot 2": 533,
    "MrP Upper Rock Room Bean Spot 3": 534,
    "MrP Upper Rock Room Bean Spot 4": 535,
    "DzS Mini/Mole Mario Tutorial Room Block 1": 601,
    "DzS Mini/Mole Mario Tutorial Room Block 2": 602,
    "DzS Mini/Mole Mario Tutorial Room Block 3": 603,
    "DzS Mini/Mole Mario Tutorial Room Block 4": 604,
    "DzS Mini/Mole Mario Tutorial Room Block 5": 605,
    "DzS Mini/Mole Mario Tutorial Room Block 6": 606,
    "DzS Mini/Mole Mario Tutorial Room Block 7": 607,
    "DwS Outside Rose Broquet Block 1": 608,
    "DwS Outside Rose Broquet Block 2": 609,
    "DwS Outside Rose Broquet Block 3": 610,
    "DwS Outside Rose Broquet Block 4": 611,
    "DwS Above Dream Egg Dreampoint Block 1": 612,
    "DwS Above Dream Egg Dreampoint Block 2": 613,
    "DwS Beach Entrance Block 1": 614,
    "DwS Beach Entrance Block 2": 615,
    "DwS Beach Entrance Block 3": 616,
    "DwS Beach Entrance Block 4": 617,
    "DwS Guard Room Block 1": 618,
    "DwS Guard Room Block 2": 619,
    "DwS Guard Room Block 3": 620,
    "DwS Seabury Dreampoint Room Block 1": 621,
    "DwS Seabury Dreampoint Room Block 2": 622,
    "DwS Seabury Dreampoint Room Block 3": 623,
    "DzS Badge Room Block 1": 624,
    "DzS Badge Room Block 2": 625,
    "DzS Badge Room Block 3": 626,
    "DzS Desert Entrance Block 1": 627,
    "DzS Desert Entrance Block 2": 628,
    "DzS Desert Entrance Block 3": 629,
    "DzS Britta's Meeting Room Block 1": 630,
    "DzS Britta's Meeting Room Block 2": 631,
    "DDzS First Dozite Entrance Block 1": 632,
    "DDzS First Dozite Entrance Block 2": 633,
    "DDzS First Dozite Learn Luigination Block": 634,
    "DDwS Seabury Entrance Block 1": 635,
    "DDwS Seabury Entrance Block 2": 636,
    "DDwS Seabury Puzzle Block": 637,
    "DDwS Seabury Cutscene Block": 638,
    "DDwS Ball Hop Dream World Block 1": 639,
    "DDwS Ball Hop Dream World Block 2": 640,
    "DzS/DwS Entrance Bean Spot": 641,
    "DzS Mini/Mole Mario Tutorial Room Bean Spot 1": 642,
    "DzS Mini/Mole Mario Tutorial Room Bean Spot 2": 643,
    "DwS Outside Rose Broquet Bean Spot": 644,
    "DwS Guard Room Bean Spot": 645,
    "DwS Seabury Dreampoint Room Bean Spot 1": 646,
    "DwS Seabury Dreampoint Room Bean Spot 2": 647,
    "DzS Badge Room Bean Spot": 648,
    "DzS Desert Entrance Bean Spot": 649,
    "DzS Britta's Meeting Room Bean Spot": 650,
    "DzS Western Track Room Block 1": 701,
    "DzS Western Track Room Block 2": 702,
    "DzS Western Track Room Block 3": 703,
    "DzS Western Track Room Block 4": 704,
    "DzS Drill Machine Tutorial Room Block 1": 705,
    "DzS Drill Machine Tutorial Room Block 2": 706,
    "DzS Drill Machine Tutorial Room Block 3": 707,
    "DzS Middle Track Room Block 1": 708,
    "DzS Middle Track Room Block 2": 709,
    "DzS Middle Track Room Block 3": 710,
    "DzS Middle Track Room Block 4": 711,
    "DzS Middle Track Room Block 5": 712,
    "DzS Middle Track Room Block 6": 713,
    "DzS Upper Track Room Block 1": 714,
    "DzS Upper Track Room Block 2": 715,
    "DzS Upper Track Room Block 3": 716,
    "DzS Tracks Mini Mario Room Block 1": 717,
    "DzS Tracks Mini Mario Room Block 2": 718,
    "DzS Tracks Mini Mario Room Block 3": 719,
    "DzS Tracks Mini Mario Room Block 4": 720,
    "DzS Tracks Mini Mario Room Block 5": 721,
    "DzS Tracks Mini Mario Room Block 6": 722,
    "DzS Southeast Track Room Block 1": 723,
    "DzS Southeast Track Room Block 2": 724,
    "DzS Southeast Track Room Block 3": 725,
    "DzS Southeast Track Room Block 4": 726,
    "DzS Southeast Track Room Block 5": 727,
    "DzS Southeast Track Room Block 6": 728,
    "DzS Southeast Track Room Block 7": 729,
    "DzS Southeast Track Room Block 8": 730,
    "DzS East Track Room Block": 731,
    "DDzS First Track Deco Pi'illo Room 2 Block": 732,
    "DDzS First Track Deco Pi'illo Room 3 Block": 733,
    "DDzS Second Track Deco Pi'illo Block 1": 734,
    "DDzS Second Track Deco Pi'illo Block 2": 735,
    "DDzS West Track Deco Pi'illo Block 1": 736,
    "DDzS West Track Deco Pi'illo Block 2": 737,
    "DDzS Final Track Deco Pi'illo Room 3 Block": 738,
    "DDzS Southeast Track Room Pi'illo Block": 739,
    "DDzS Eastern Track Room Pi'illo Block 1": 740,
    "DDzS Eastern Track Room Pi'illo Block 2": 741,
    "DzS East End of Track Block 1": 742,
    "DzS East End of Track Block 2": 743,
    "DzS West End of Track Block 1": 744,
    "DzS West End of Track Block 2": 745,
    "DzS West End of Track Block 3": 746,
    "DzS West End of Track Block 4": 747,
    "DzS West End of Track Block 5": 748,
    "DzS Track Area Entrance Block 1": 749,
    "DzS Track Area Entrance Block 2": 750,
    "DzS Track Area Entrance Block 3": 751,
    "DzS Western Track Room Bean Spot 1": 752,
    "DzS Western Track Room Bean Spot 2": 753,
    "DzS Drill Machine Tutorial Room Bean Spot 1": 754,
    "DzS Drill Machine Tutorial Room Bean Spot 2": 755,
    "DzS Middle Track Room Bean Spot 1": 756,
    "DzS Middle Track Room Bean Spot 2": 757,
    "DzS Upper Track Room Bean Spot 1": 758,
    "DzS Upper Track Room Bean Spot 2": 759,
    "DzS Upper Track Room Bean Spot 3": 760,
    "DzS Upper Track Room Bean Spot 4": 761,
    "DzS Southeast Track Room Bean Spot": 762,
    "DzS East Track Room Bean Spot": 763,
    "DzS West End of Track Bean Spot 1": 764,
    "DzS West End of Track Bean Spot 2": 765,
    "DzS West End of Track Bean Spot 3": 766,
    "DzS West End of Track Bean Spot 4": 767,
    "DzS West End of Track Bean Spot 5": 768,
    "DzS West End of Track Bean Spot 6": 769,
    "DzS Track Area Entrance Bean Spot 1": 770,
    "DzS Track Area Entrance Bean Spot 2": 771,
    "DzS Track Area Entrance Bean Spot 3": 772,
    "DzS East of Dreamstone Block 1": 801,
    "DzS East of Dreamstone Block 2": 802,
    "DzS Eastern Badge Room Block": 803,
    "DzS Ultibed Cliff Block 1": 804,
    "DzS Ultibed Cliff Block 2": 805,
    "DDzS Dream Stone First Drill Room Block": 806,
    "DDzS Dream Stone Big Drill Room Block 1": 807,
    "DDzS Dream Stone Big Drill Room Block 2": 808,
    "DDzS Dream Stone After Big Drill Room Block 1": 809,
    "DDzS Dream Stone After Big Drill Room Block 2": 810,
    "DDzS Dream Stone After Big Drill Room Block 3": 811,
    "DDzS Dream Stone After Big Drill Room Block 4": 812,
    "DDzS Dream Stone First Luiginary Room Block": 813,
    "DDzS Dream Stone Switch Puzzle Room 1 Block": 814,
    "DDzS Dream Stone After Second Spirit Talk Block 1": 815,
    "DDzS Dream Stone After Second Spirit Talk Block 2": 816,
    "DDzS Dream Stone After Second Spirit Talk Block 3": 817,
    "DDzS Dream Stone Horizontal Drill Room Block 1": 818,
    "DDzS Dream Stone Horizontal Drill Room Block 2": 819,
    "DDzS Dream Stone Ground Pound Tutorial Room Block": 820,
    "DDzS Dream Stone Dream Last Attack Pieces Block 1": 821,
    "DDzS Dream Stone Dream Last Attack Pieces Block 2": 822,
    "DDzS Dream Stone Dream Last Attack Pieces Block 3": 823,
    "DDzS Dream Stone Dream Last Attack Pieces Block 4": 824,
    "DDzS Mattress Dream Bottom Room Block 1": 825,
    "DDzS Mattress Dream Bottom Room Block 2": 826,
    "DDzS Mattress Dream Bottom Room Block 3": 827,
    "DDzS Mattress Dream Top Room Block": 828,
    "DDzS Badge Room Pi'illo Block 1": 829,
    "DDzS Badge Room Pi'illo Block 2": 830,
    "DzS Dreamstone Resting Spot Block": 831,
    "DzS Dozing Mattress Underground 1 Block 1": 832,
    "DzS Dozing Mattress Underground 1 Block 2": 833,
    "DzS Dozing Mattress Underground 1 Block 3": 834,
    "DzS Dozing Mattress Underground 2 Block 1": 835,
    "DzS Dozing Mattress Underground 2 Block 2": 836,
    "DzS Dozing Mattress Path to Underground Block 1": 837,
    "DzS Dozing Mattress Path to Underground Block 2": 838,
    "DzS Ultibed Cliff Bean Spot 1": 839,
    "DzS Ultibed Cliff Bean Spot 2": 840,
    "DzS Dreamstone Resting Spot Bean Spot": 841,
    "DzS Dozing Mattress Underground 1 Bean Spot": 842,
    "DzS Dozing Mattress Path to Underground Bean Spot": 843,
    "Wp Entrance Block 1": 901,
    "Wp Entrance Block 2": 902,
    "Wp Mole Mario Pi'illo Room Block 1": 903,
    "Wp Mole Mario Pi'illo Room Block 2": 904,
    "Wp Mole Mario Pi'illo Room Block 3": 905,
    "Wp Shopping District Block 1": 906,
    "Wp Shopping District Block 2": 907,
    "Wp Shopping District Block 3": 908,
    "Wp Shopping District Block 4": 909,
    "Wp Shopping District Block 5": 910,
    "Wp Shopping District Block 6": 911,
    "Wp Southern Panel Room Block 1": 912,
    "Wp Southern Panel Room Block 2": 913,
    "Wp Southern Panel Room Block 3": 914,
    "Wp Southern Panel Room Block 4": 915,
    "Wp Southern Panel Room Block 5": 916,
    "Wp Southern Panel Room Block 6": 917,
    "Wp Southern Panel Room Block 7": 918,
    "Wp Entrance Right Building Block": 919,
    "Wp Entrance Middle Building Block 1": 920,
    "Wp Entrance Middle Building Block 2": 921,
    "Wp Entrance Left Building Block": 922,
    "Wp Pi'illo Collector's House Block": 923,
    "Wp Kylie Koopa's Photo Booth Block": 924,
    "DWp Massif Lobby Block 1": 925,
    "DWp Massif Lobby Block 2": 926,
    "DWp Massif Topright of Main Block": 927,
    "DWp Massif Clock Tutorial Block": 928,
    "DWp Massif After Clock Tutorial Block 1": 929,
    "DWp Massif After Clock Tutorial Block 2": 930,
    "DWp Massif After Clock Tutorial Block 3": 931,
    "DWp Massif Heavy Zest Room 1 Block 1": 932,
    "DWp Massif Heavy Zest Room 1 Block 2": 933,
    "DWp Massif Heavy Zest Room 1 Block 3": 934,
    "DWp Massif Heavy Zest Room 2 Block 1": 935,
    "DWp Massif Heavy Zest Room 2 Block 2": 936,
    "DWp Massif Heavy Zest Room 3 Block 1": 937,
    "DWp Massif Heavy Zest Room 3 Block 2": 938,
    "DWp Massif Heavy Zest Room 3 Block 3": 939,
    "DWp Massif Heavy Zest Room 3 Block 4": 940,
    "DWp Massif Heavy Zest Room 3 Block 5": 941,
    "DWp Massif Thunder Sass Room 1 Block 1": 942,
    "DWp Massif Thunder Sass Room 1 Block 2": 943,
    "DWp Massif Thunder Sass Room 3 Block 1": 944,
    "DWp Massif Thunder Sass Room 3 Block 2": 945,
    "DWp Massif Top Left of Main Room 2 Block 1": 946,
    "DWp Massif Top Left of Main Room 2 Block 2": 947,
    "DWp Massif Sorrow Fist Room 3 Block 1": 948,
    "DWp Massif Sorrow Fist Room 3 Block 2": 949,
    "DWp South Room Pi'illo Block 1": 950,
    "DWp South Room Pi'illo Block 2": 951,
    "DWp After Puzzle Pi'illo Room 2 Block": 952,
    "Wp Massif Resting Spot Block": 953,
    "Wp Entrance Bean Spot": 954,
    "Wp Mole Mario Pi'illo Room Bean Spot 1": 955,
    "Wp Mole Mario Pi'illo Room Bean Spot 2": 956,
    "Wp Shopping District Bean Spot 1": 957,
    "Wp Shopping District Bean Spot 2": 958,
    "Wp Wiggler's Resting Spot Block 1": 1001,
    "Wp Wiggler's Resting Spot Block 2": 1002,
    "Wp Pi'illo Collector's Basement Block 1": 1003,
    "Wp Pi'illo Collector's Basement Block 2": 1004,
    "Wp Pi'illo Collector's Basement Block 3": 1005,
    "Wp Pi'illo Collector's Basement Block 4": 1006,
    "DWp Bedsmith Entrance Block": 1007,
    "DWp Bedsmith Room 2 Block": 1008,
    "DWp Bedsmith Room 3 Block 1": 1009,
    "DWp Bedsmith Room 3 Block 2": 1010,
    "DWp Bedsmith Room 3 Block 3": 1011,
    "DWp Bedsmith Room 4 Block 1": 1012,
    "DWp Bedsmith Room 4 Block 2": 1013,
    "DWp Bedsmith Room 4 Detour Block 1": 1014,
    "DWp Bedsmith Room 4 Detour Block 2": 1015,
    "DWp Bedsmith Room 5 Block": 1016,
    "DWp Bedsmith Room 6 Block 1": 1017,
    "DWp Bedsmith Room 6 Block 2": 1018,
    "DWp Bedsmith Room 6 Block 3": 1019,
    "DWp Bedsmith Upper Umbrella Puzzle Block 1": 1020,
    "DWp Bedsmith Upper Umbrella Puzzle Block 2": 1021,
    "DWp Bedsmith Upper Umbrella Puzzle Block 3": 1022,
    "DWp Right of Wiggler Pi'illo Room 2 Block": 1023,
    "DWp Bedsmith Umbrella Puzzle Basement Block 1": 1024,
    "DWp Bedsmith Umbrella Puzzle Basement Block 2": 1025,
    "DWp Bedsmith Umbrella Puzzle Basement Block 3": 1026,
    "DWp Bedsmith Umbrella Puzzle Basement Block 4": 1027,
    "DWp Bedsmith Stack Bomb Detour Block 1": 1028,
    "DWp Bedsmith Stack Bomb Detour Block 2": 1029,
    "DWp Bedsmith Stack Bomb Detour Block 3": 1030,
    "Wp Mole Mario Pi'illo Room Roof Bean Spot": 1031,
    "Wp Wiggler's Resting Spot Bean Spot 1": 1032,
    "Wp Wiggler's Resting Spot Bean Spot 2": 1033,
    "Wp Wiggler's Resting Spot Bean Spot 3": 1034,
    "MtP Entrance Block 1": 1101,
    "MtP Entrance Block 2": 1102,
    "MtP Entrance Block 3": 1103,
    "MtP First Mega Pi'illo Room Block 1": 1201,
    "MtP First Mega Pi'illo Room Block 2": 1202,
    "MtP Weird Lift Thingy Block 1": 1203,
    "MtP Weird Lift Thingy Block 2": 1204,
    "MtP 2 Pi'illos in Rocks Block 1": 1205,
    "MtP 2 Pi'illos in Rocks Block 2": 1206,
    "MtP Second Weird Lift Thingy Block": 1207,
    "MtP Spin Jump Tutorial Block 1": 1208,
    "MtP Spin Jump Tutorial Block 2": 1209,
    "MtP Spin Jump Tutorial Block 3": 1210,
    "MtP Spin Jump Tutorial Block 4": 1211,
    "MtP Southeast Deviation Block 1": 1212,
    "MtP Southeast Deviation Block 2": 1213,
    "MtP Southeast Deviation Block 3": 1214,
    "MtP Southeast Deviation Block 4": 1215,
    "MtP Southeast Deviation Block 5": 1216,
    "MtP Southwest Spin Jump Gaps Block 1": 1217,
    "MtP Southwest Spin Jump Gaps Block 2": 1218,
    "MtP Spin Jump Whirlwind Tutorial Block": 1219,
    "MtP West of Whirlwind Block 1": 1220,
    "MtP West of Whirlwind Block 2": 1221,
    "MtP West of Whirlwind Block 3": 1222,
    "MtP West of Whirlwind Block 4": 1223,
    "MtP Lower Peak Before Big Jump Block 1": 1224,
    "MtP Lower Peak Before Big Jump Block 2": 1225,
    "MtP Lower Peak Before Big Jump Block 3": 1226,
    "MtP Lower Peak Before Big Jump Block 4": 1227,
    "MtP Lower Peak Before Big Jump Block 5": 1228,
    "MtP Lower Peak Before Big Jump Block 6": 1229,
    "MtP Ball Hop Cave Block 1": 1230,
    "MtP Ball Hop Cave Block 2": 1231,
    "DMtP Base Right Mega Pi'illo Entrance Block 1": 1232,
    "DMtP Base Right Mega Pi'illo Entrance Block 2": 1233,
    "DMtP Base Right Mega Pi'illo Learn Cone Block": 1234,
    "DMtP Base Left Mega Pi'illo Block 1": 1235,
    "DMtP Base Left Mega Pi'illo Block 2": 1236,
    "DMtP Base Left Mega Pi'illo Block 3": 1237,
    "DMtP Base Left Mega Pi'illo Block 4": 1238,
    "DMtP Base Left Mega Pi'illo Block 5": 1239,
    "DMtP Multi-Access Pi'illo Block 1": 1240,
    "DMtP Multi-Access Pi'illo Block 2": 1241,
    "DMtP Multi-Access Pi'illo Block 3": 1242,
    "DMtP Right Branching Path Pi'illo Block 1": 1243,
    "DMtP Right Branching Path Pi'illo Block 2": 1244,
    "MtP Weird Lift Thingy Bean Spot 1": 1245,
    "MtP Weird Lift Thingy Bean Spot 2": 1246,
    "MtP Second Weird Lift Thingy Bean Spot 1": 1247,
    "MtP Second Weird Lift Thingy Bean Spot 2": 1248,
    "MtP Spin Jump Tutorial Bean Spot": 1249,
    "MtP Southeast Deviation Bean Spot": 1250,
    "MtP Spin Jump Whirlwind Tutorial Bean Spot": 1251,
    "MtP West of Whirlwind Bean Spot": 1252,
    "MtP Lower Peak Before Big Jump Bean Spot 1": 1253,
    "MtP Lower Peak Before Big Jump Bean Spot 2": 1254,
    "MtP Lower Peak Before Big Jump Bean Spot 3": 1255,
    "MtP Ball Hop Cave Bean Spot": 1256,
    "MtP Side Drill Tutorial Block 1": 1301,
    "MtP Side Drill Tutorial Block 2": 1302,
    "MtP Large Room Before Snow Block 1": 1303,
    "MtP Large Room Before Snow Block 2": 1304,
    "MtP Large Room Before Snow Block 3": 1305,
    "MtP Path to Right Massif Ice Room Block": 1306,
    "MtP Right Massif Ice Room Block 1": 1307,
    "MtP Right Massif Ice Room Block 2": 1308,
    "MtP Right Massif Ice Room Block 3": 1309,
    "MtP Right Massif Ice Room Block 4": 1310,
    "MtP Tricky Spinjump Detour Block 1": 1311,
    "MtP Tricky Spinjump Detour Block 2": 1312,
    "MtP Path to Left Massif Ice Room Block": 1313,
    "MtP Left Massif Ice Room Block 1": 1314,
    "MtP Left Massif Ice Room Block 2": 1315,
    "MtP Left Massif Ice Room Block 3": 1316,
    "MtP Summit Ball Hop Gate Block 1": 1317,
    "MtP Summit Ball Hop Gate Block 2": 1318,
    "MtP Pajamaja Rock Frame Resting Spot Block 1": 1319,
    "MtP Pajamaja Rock Frame Resting Spot Block 2": 1320,
    "MtP Pajamaja Rock Frame Resting Spot Block 3": 1321,
    "MtP Ball Hop Tutorial Block": 1322,
    "DMtP Pajamaja Rock Frame Room 2 Block": 1323,
    "DMtP Pajamaja Rock Frame Timed Switch Room Block": 1324,
    "MtP Large Room Before Snow Bean Spot": 1325,
    "MtP Path to Right Massif Ice Room Bean Spot": 1326,
    "MtP Right Massif Ice Room Bean Spot 1": 1327,
    "MtP Right Massif Ice Room Bean Spot 2": 1328,
    "MtP Tricky Spinjump Detour Bean Spot": 1329,
    "MtP Left Massif Ice Room Bean Spot 1": 1330,
    "MtP Left Massif Ice Room Bean Spot 2": 1331,
    "MtP Ball Hop Tutorial Bean Spot 1": 1332,
    "MtP Ball Hop Tutorial Bean Spot 2": 1333,
    "MtP Peak Mega Pi'illo Room Block": 1401,
    "MtP Cliff in Path to Left Massif Ice Room Block": 1402,
    "DMtP Peak Left Mega Pi'illo Room 2 Block": 1403,
    "DMtP Peak Left Mega Pi'illo Room 3 Block": 1404,
    "DMtP Peak Right Mega Pi'illo Entrance Block 1": 1405,
    "DMtP Peak Right Mega Pi'illo Entrance Block 2": 1406,
    "MtP Peak Bean Spot": 1407,
    "MtP Frozen Dream World Spot Bean Spot 1": 1408,
    "MtP Frozen Dream World Spot Bean Spot 2": 1409,
    "DMtP Summit Massif Shop Block": 1501,
    "DMtP Summit Room 4 Block 1": 1502,
    "DMtP Summit Room 4 Block 2": 1503,
    "DMtP Summit Room 4 Block 3": 1504,
    "DMtP Summit Room 4 Block 4": 1505,
    "DMtP Summit Room 4 Block 5": 1506,
    "DMtP Summit Room 4 Block 6": 1507,
    "DMtP Summit Room 4 Block 7": 1508,
    "DMtP Summit Room 5 Block 1": 1509,
    "DMtP Summit Room 5 Block 2": 1510,
    "DMtP Summit Room 5 Block 3": 1511,
    "DMtP Summit Room 5 Block 4": 1512,
    "DMtP Summit Room 5 Block 5": 1513,
    "DMtP Summit Room 6 Block 1": 1514,
    "DMtP Summit Room 6 Block 2": 1515,
    "DMtP Summit Room 6 Block 3": 1516,
    "DMtP Summit Room 6 Block 4": 1517,
    "DMtP Summit Room 6 Block 5": 1518,
    "DMtP Summit Room 7 Block 1": 1519,
    "DMtP Summit Room 7 Block 2": 1520,
    "DMtP Summit Room 8 Block 1": 1521,
    "DMtP Summit Room 8 Block 2": 1522,
    "DMtP Summit Room 8 Block 3": 1523,
    "DMtP Summit Room 8 Block 4": 1524,
    "DMtP Summit Room 8 Detour Block 1": 1525,
    "DMtP Summit Room 8 Detour Block 2": 1526,
    "DMtP Summit Room 9 Block": 1527,
    "DMtP Summit Room 9 Detour Block 1": 1528,
    "DMtP Summit Room 9 Detour Block 2": 1529,
    "DMtP Summit Room 9 Detour Block 3": 1530,
    "DMtP Summit Room 9 Detour Block 4": 1531,
    "DMtP Summit Room 9 Detour Block 5": 1532,
    "DMtP Summit Learn Cone Storm Block": 1533,
    "DMtP Summit Fountain Room Block 1": 1534,
    "DMtP Summit Fountain Room Block 2": 1535,
    "DMtP Summit Between Fountain and Shop Block 1": 1536,
    "DMtP Summit Between Fountain and Shop Block 2": 1537,
    "DMtP Summit After Fountain 1 Block 1": 1538,
    "DMtP Summit After Fountain 1 Block 2": 1539,
    "DMtP Summit After Fountain 3 Block 1": 1540,
    "DMtP Summit After Fountain 3 Block 2": 1541,
    "DMtP Summit After Fountain 3 Block 3": 1542,
    "DMtP Summit After Fountain 3 Block 4": 1543,
    "DMtP Summit After Fountain 3 Block 5": 1544,
    "DMtP Summit After Fountain 3 Detour Block 1": 1545,
    "DMtP Summit After Fountain 3 Detour Block 2": 1546,
    "DMtP Summit After Fountain 3 Detour Block 3": 1547,
    "DMtP Summit After Fountain 4 Block 1": 1548,
    "DMtP Summit After Fountain 4 Block 2": 1549,
    "DMtP Summit Before Arena Block 1": 1550,
    "DMtP Summit Before Arena Block 2": 1551,
    "DMtP Summit Arena Block": 1552,
    "DMtP Summit Room 3 Block 1": 1553,
    "DMtP Summit Room 3 Block 2": 1554,
    "DwS Dream Egg Dreampoint Room Block 1": 1601,
    "DwS Dream Egg Dreampoint Room Block 2": 1602,
    "DwS Dream Egg Dreampoint Room Block 3": 1603,
    "DwS Dream Egg Dreampoint Room Block 4": 1604,
    "DwS Crab Minigame Block 1": 1605,
    "DwS Crab Minigame Block 2": 1606,
    "DwS Ultibed Cave Entrance Block 1": 1607,
    "DwS Ultibed Cave Entrance Block 2": 1608,
    "DwS Ultibed Cave Entrance Block 3": 1609,
    "DwS Ultibed Cave Entrance Block 4": 1610,
    "DwS Ultibed Cave Middle Room Block": 1611,
    "DwS Seabelle Dreampoint Block 1": 1612,
    "DwS Seabelle Dreampoint Block 2": 1613,
    "DwS Seabelle Dreampoint Block 3": 1614,
    "DwS Seabelle Dreampoint Block 4": 1615,
    "DwS Middle Warp Pipe Room Block 1": 1616,
    "DwS Middle Warp Pipe Room Block 2": 1617,
    "DwS Middle Warp Pipe Room Block 3": 1618,
    "DwS Middle Warp Pipe Room Block 4": 1619,
    "DDwS Dream Egg Dream Entrance Block": 1620,
    "DDwS Seatoon Cutscene Block": 1621,
    "DDwS Seabelle Cutscene Block": 1622,
    "DDwS After Seabelle Pi'illo Branch Block 1": 1623,
    "DDwS After Seabelle Pi'illo Branch Block 2": 1624,
    "DDwS After Seabelle Pi'illo Branch Block 3": 1625,
    "DDwS After Seabelle Pi'illo Branch Block 4": 1626,
    "DDwS After Seabelle Pi'illo Right Room Block": 1627,
    "DDwS Ultibed Path Pi'illo Block": 1628,
    "DwS Driftwood Jelly Sheets Resting Spot Bean Spot 1": 1629,
    "DwS Driftwood Jelly Sheets Resting Spot Bean Spot 2": 1630,
    "DwS Seabelle Dreampoint Bean Spot 1": 1631,
    "DwS Seabelle Dreampoint Bean Spot 2": 1632,
    "DwS Middle Warp Pipe Room Bean Spot 1": 1633,
    "DwS Middle Warp Pipe Room Bean Spot 2": 1634,
    "DDwS Dream Egg Dream First Egg Entrance Block": 1701,
    "DDwS Dream Egg Dream First Egg Room 2 Block 1": 1702,
    "DDwS Dream Egg Dream First Egg Room 2 Block 2": 1703,
    "DDwS Dream Egg Dream First Egg Room 2 Block 3": 1704,
    "DDwS Dream Egg Dream First Egg Room 2 Block 4": 1705,
    "DDwS Dream Egg Dream First Egg Room 3 Block 1": 1706,
    "DDwS Dream Egg Dream First Egg Room 3 Block 2": 1707,
    "DDwS Dream Egg Dream Second Egg Room 1 Block": 1708,
    "DDwS Dream Egg Dream Second Egg Room 2 Side Room Block 1": 1709,
    "DDwS Dream Egg Dream Second Egg Room 2 Side Room Block 2": 1710,
    "DDwS Dream Egg Dream Second Egg Room 2 Side Room Block 3": 1711,
    "DDwS Dream Egg Dream Second Egg Room 4 Block 1": 1712,
    "DDwS Dream Egg Dream Second Egg Room 4 Block 2": 1713,
    "DDwS Dream Egg Dream Second Egg Room 5 Block 1": 1714,
    "DDwS Dream Egg Dream Second Egg Room 5 Block 2": 1715,
    "DDwS Dream Egg Dream Second Egg Room 5 Block 3": 1716,
    "DDwS Dream Egg Dream Second Egg Room 5 Block 4": 1717,
    "DDwS Dream Egg Dream Second Egg Room 6 Block 1": 1718,
    "DDwS Dream Egg Dream Second Egg Room 6 Block 2": 1719,
    "DDwS Dream Egg Dream Third Egg Room 1 Block": 1720,
    "DDwS Dream Egg Dream Third Egg Room 3 Block": 1721,
    "DDwS Dream Egg Dream First Egg Room 2 Side Room Block 1": 1722,
    "DDwS Dream Egg Dream First Egg Room 2 Side Room Block 2": 1723,
    "DDwS Dream Egg Dream First Egg Room 2 Side Room Block 3": 1724,
    "DDwS Dream Egg Dream Second Egg Entrance Block": 1725,
    "DDwS Dream Egg Dream Third Egg Entrance Block": 1726,
    "DDwS Dream Egg Dream Second Egg Room 2 Block": 1727,
    "DDwS Dream Egg Dream Second Egg Room 3 Block": 1728,
    "SmW Woods Entrance Block 1": 1801,
    "SmW Woods Entrance Block 2": 1802,
    "SmW Bedsmith Room Block 1": 1803,
    "SmW Bedsmith Room Block 2": 1804,
    "SmW Poison Water Puzzle 1 Block 1": 1805,
    "SmW Poison Water Puzzle 1 Block 2": 1806,
    "SmW Poison Water Puzzle 2 Block 1": 1807,
    "SmW Poison Water Puzzle 2 Block 2": 1808,
    "SmW Poison Water Puzzle 2 Block 3": 1809,
    "SmW Poison Water Puzzle 2 Block 4": 1810,
    "SmW Side Drill Junction Block 1": 1811,
    "SmW Side Drill Junction Block 2": 1812,
    "SmW First Pi'illo Master Room Block 1": 1813,
    "SmW First Pi'illo Master Room Block 2": 1814,
    "DSmW Lower Elevator Pi'illo Block 1": 1815,
    "DSmW Lower Elevator Pi'illo Block 2": 1816,
    "DSmW Lower Elevator Pi'illo Block 3": 1817,
    "DSmW Other Pi'illo in First Master Room Block": 1818,
    "DSmW Poison Water Pi'illo Block 1": 1819,
    "DSmW Poison Water Pi'illo Block 2": 1820,
    "SmW Woods Entrance Bean Spot": 1821,
    "SmW Poison Water Puzzle 1 Bean Spot": 1822,
    "SmW Side Drill Junction Bean Spot 1": 1823,
    "SmW Side Drill Junction Bean Spot 2": 1824,
    "SmW Lower Elevator Room Block 1": 1901,
    "SmW Lower Elevator Room Block 2": 1902,
    "SmW Bottom Right Track Room Block 1": 1903,
    "SmW Bottom Right Track Room Block 2": 1904,
    "SmW Bottom Right Pi'illo Master Room Block 1": 1905,
    "SmW Bottom Right Pi'illo Master Room Block 2": 1906,
    "SmW Middle Right Track Room Block 1": 1907,
    "SmW Middle Right Track Room Block 2": 1908,
    "SmW Top Right Track Room Block 1": 1909,
    "SmW Top Right Track Room Block 2": 1910,
    "SmW Bottom Left Track Room Block 1": 1911,
    "SmW Bottom Left Track Room Block 2": 1912,
    "SmW Middle Left Track Room Block": 1913,
    "SmW Top Left Track Room Entrance Block 1": 1914,
    "SmW Top Left Track Room Entrance Block 2": 1915,
    "SmW Top Left Track Room Cave Block 1": 1916,
    "SmW Top Left Track Room Cave Block 2": 1917,
    "SmW Top Left Track Room Cave Block 3": 1918,
    "DSmW Pi'illo Master 1 Block 1": 1919,
    "DSmW Pi'illo Master 1 Block 2": 1920,
    "DSmW Pi'illo Master 2 Room 1 Block": 1921,
    "DSmW Pi'illo Master 2 Room 2 Block 1": 1922,
    "DSmW Pi'illo Master 2 Room 2 Block 2": 1923,
    "DSmW Pi'illo Master 2 Room 2 Block 3": 1924,
    "DSmW Pi'illo Master 2 Room 2 Block 4": 1925,
    "DSmW Southeast Pi'illo Master Room 1 Block": 1926,
    "DSmW Southwest Pi'illo Master Room 1 Block 1": 1927,
    "DSmW Southwest Pi'illo Master Room 1 Block 2": 1928,
    "DSmW West Pi'illo Master Room 1 Block": 1929,
    "DSmW West Pi'illo Master Room 2 Block 1": 1930,
    "DSmW West Pi'illo Master Room 2 Block 2": 1931,
    "DSmW West Pi'illo Master Room 2 Block 3": 1932,
    "DSmW Upper Double Pi'illo Block 1": 1933,
    "DSmW Upper Double Pi'illo Block 2": 1934,
    "DSmW Lower Double Pi'illo Block": 1935,
    "SmW Bottom Right Track Room Bean Spot": 1936,
    "SmW Middle Right Track Room Bean Spot": 1937,
    "SmW Top Right Track Room Bean Spot": 1938,
    "SmW Top Left Track Room Entrance Bean Spot": 1939,
    "SmW Top Left Track Room Pi'illo Bean Spot": 1940,
    "SmW Top Left Track Room Cave Bean Spot 1": 1941,
    "SmW Top Left Track Room Cave Bean Spot 2": 1942,
    "SmW Top Left Track Room Cave Bean Spot 3": 1943,
    "DSmW Zeekeeper Resting Spot Before Boss Block": 2001,
    "SmW Puzzle Track Area Block": 2002,
    "SmW Room Before Pi'illodium Block 1": 2003,
    "SmW Room Before Pi'illodium Block 2": 2004,
    "SmW Room Before Pi'illodium Block 3": 2005,
    "SmW Room Before Pi'illodium Block 4": 2006,
    "DSmW Zeekeeper Resting Spot Wrong Path Block": 2007,
    "DSmW Zeekeeper Resting Spot Monster Path Block 1": 2008,
    "DSmW Zeekeeper Resting Spot Monster Path Block 2": 2009,
    "DSmW Zeekeeper Resting Spot Monster Path Block 3": 2010,
    "DSmW Zeekeeper Resting Spot After Correct Path Block": 2011,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 1": 2012,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 2": 2013,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 3": 2014,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 4": 2015,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 5": 2016,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 6": 2017,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 7": 2018,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 8": 2019,
    "DSmW Zeekeeper Resting Spot Many Pipe Room Block 9": 2020,
    "DSmW Zeekeeper Resting Spot First Windy Room Block": 2021,
    "DSmW Zeekeeper Resting Spot Vertical Windy Room Block 1": 2022,
    "DSmW Zeekeeper Resting Spot Vertical Windy Room Block 2": 2023,
    "DSmW Zeekeeper Resting Spot Vertical Windy Room Block 3": 2024,
    "DSmW Zeekeeper Resting Spot First Luigination Room Block": 2025,
    "DSmW Zeekeeper Resting Spot Large Sneeze Room Block 1": 2026,
    "DSmW Zeekeeper Resting Spot Large Sneeze Room Block 2": 2027,
    "DSmW Zeekeeper Resting Spot Large Sneeze Room Block 3": 2028,
    "DSmW Zeekeeper Resting Spot Large Sneeze Room Block 4": 2029,
    "DSmW Zeekeeper Resting Spot Large Luigination Room Block 1": 2030,
    "DSmW Zeekeeper Resting Spot Large Luigination Room Block 2": 2031,
    "DSmW Zeekeeper Resting Spot Right Moustache Room Block 1": 2032,
    "DSmW Zeekeeper Resting Spot Right Moustache Room Block 2": 2033,
    "DSmW Zeekeeper Resting Spot Right Moustache Room Block 3": 2034,
    "DSmW Zeekeeper Resting Spot Right Moustache Room Block 4": 2035,
    "DSmW Zeekeeper Resting Spot Left Moustache Room Block 1": 2036,
    "DSmW Zeekeeper Resting Spot Left Moustache Room Block 2": 2037,
    "DSmW Zeekeeper Resting Spot Left Moustache Room Block 3": 2038,
    "DSmW Zeekeeper Resting Spot Left Moustache Room Block 4": 2039,
    "DSmW Zeekeeper Resting Spot Left Moustache Room Block 5": 2040,
    "DSmW Zeekeeper Resting Spot 1-2 Reference Block 1": 2041,
    "DSmW Zeekeeper Resting Spot 1-2 Reference Block 2": 2042,
    "DSmW Zeekeeper Resting Spot 1-2 Reference Block 3": 2043,
    "SmW Room Before Pi'illodium Bean Spot 1": 2044,
    "SmW Room Before Pi'illodium Bean Spot 2": 2045,
    "SmW Room Before Pi'illodium Bean Spot 3": 2046,
    "SmW Room Before Pi'illodium Bean Spot 4": 2047,
    "SmW Room Before Pi'illodium Bean Spot 5": 2048,
    "SmW Room Before Pi'illodium Bean Spot 6": 2049,
    "NBC Kamek 1 Left Room Block 1": 2101,
    "NBC Kamek 1 Left Room Block 2": 2102,
    "NBC Kamek 1 Lobby Block 1": 2103,
    "NBC Kamek 1 Lobby Block 2": 2104,
    "NBC Kamek 1 Lobby Block 3": 2105,
    "NBC Kamek 1 Right Room Block 1": 2106,
    "NBC Kamek 1 Right Room Block 2": 2107,
    "NBC Kamek 1 Top Left Block 1": 2108,
    "NBC Kamek 1 Top Left Block 2": 2109,
    "NBC Kamek 1 North of Lobby Block": 2110,
    "NBC Kamek 1 Top Right Block 1": 2111,
    "NBC Kamek 1 Top Right Block 2": 2112,
    "NBC Kamek 1 Top Right Block 3": 2113,
    "NBC Kamek 1 Top Right Block 4": 2114,
    "NBC First Elevator Lower Room Block 1": 2115,
    "NBC First Elevator Lower Room Block 2": 2116,
    "NBC First Elevator Upper Room Block": 2117,
    "NBC First Bomb Room Block 1": 2118,
    "NBC First Bomb Room Block 2": 2119,
    "NBC First Bomb Room Block 3": 2120,
    "NBC First Bomb Room Block 4": 2121,
    "NBC First Bomb Room Block 5": 2122,
    "NBC First Bomb Room Block 6": 2123,
    "NBC First Bomb Room Block 7": 2124,
    "DNBC Kamek 1 Dream Main Room Block 1": 2125,
    "DNBC Kamek 1 Dream Main Room Block 2": 2126,
    "DNBC Kamek 1 Dream Main Room Block 3": 2127,
    "DNBC Kamek 1 Dream Antigravity Intro Block 1": 2128,
    "DNBC Kamek 1 Dream Antigravity Intro Block 2": 2129,
    "DNBC Kamek 1 Dream Antigravity Intro Block 3": 2130,
    "DNBC Kamek 1 Dream Antigravity Intro Block 4": 2131,
    "DNBC Kamek 1 Dream Antigravity Intro Block 5": 2132,
    "DNBC Kamek 1 Dream Antigravity Intro Block 6": 2133,
    "DNBC Kamek 1 Dream Antigravity Intro Block 7": 2134,
    "DNBC Kamek 1 Dream Swimming Kick Intro Block 1": 2135,
    "DNBC Kamek 1 Dream Swimming Kick Intro Block 2": 2136,
    "DNBC Kamek 1 Dream Swimming Kick Intro Block 3": 2137,
    "DNBC Kamek 1 Dream Enemy Room Block 1": 2138,
    "DNBC Kamek 1 Dream Enemy Room Block 2": 2139,
    "DNBC Kamek 1 Dream Enemy Room Block 3": 2140,
    "DNBC Kamek 1 Dream Spike Maze Block 1": 2141,
    "DNBC Kamek 1 Dream Spike Maze Block 2": 2142,
    "DNBC Kamek 1 Dream Arena Block": 2143,
    "NBC Kamek 1 Top Right Bean Spot": 2144,
    "NBC First Elevator Lower Room Bean Spot 1": 2145,
    "NBC First Elevator Lower Room Bean Spot 2": 2146,
    "NBC Kamek 2 Left Room Block 1": 2201,
    "NBC Kamek 2 Left Room Block 2": 2202,
    "NBC Kamek 2 Left Room Block 3": 2203,
    "NBC Kamek 2 Left Room Block 4": 2204,
    "NBC Kamek 2 Right Room Block 1": 2205,
    "NBC Kamek 2 Right Room Block 2": 2206,
    "NBC Kamek 2 Right Room Block 3": 2207,
    "NBC Kamek 2 Right Room Block 4": 2208,
    "NBC Above Kamek 2 Block 1": 2209,
    "NBC Above Kamek 2 Block 2": 2210,
    "NBC Above Kamek 2 Block 3": 2211,
    "NBC Above Kamek 2 Block 4": 2212,
    "NBC Above Kamek 2 Block 5": 2213,
    "NBC West of Kamek 3 Block 1": 2214,
    "NBC West of Kamek 3 Block 2": 2215,
    "NBC West of Kamek 3 Block 3": 2216,
    "NBC West of Kamek 3 Block 4": 2217,
    "NBC Kamek 3 Western Bomb Room Block 1": 2218,
    "NBC Kamek 3 Western Bomb Room Block 2": 2219,
    "NBC Kamek 3 Western Bomb Room Block 3": 2220,
    "NBC Kamek 3 Eastern Bomb Room Block 1": 2221,
    "NBC Kamek 3 Eastern Bomb Room Block 2": 2222,
    "NBC Kamek 3 Eastern Bomb Room Block 3": 2223,
    "NBC Kamek 3 Eastern Bomb Room Block 4": 2224,
    "NBC Annoying Quadruple Bomb Room Block 1": 2225,
    "NBC Annoying Quadruple Bomb Room Block 2": 2226,
    "NBC Annoying Quadruple Bomb Room Block 3": 2227,
    "NBC Annoying Quadruple Bomb Room Block 4": 2228,
    "NBC Annoying Quadruple Bomb Room Block 5": 2229,
    "DNBC Kamek 2 Dream Door Block": 2230,
    "DNBC Kamek 2 Dream Rising Lava Block": 2231,
    "DNBC Kamek 2 Dream Before Arena Block": 2232,
    "DNBC Kamek 2 Dream Arena Block": 2233,
    "DNBC Kamek 3 Dream Entrance Block 1": 2234,
    "DNBC Kamek 3 Dream Entrance Block 2": 2235,
    "DNBC Kamek 3 Dream Room 2 Block": 2236,
    "DNBC Kamek 3 Dream Room 3 Block": 2237,
    "DNBC Kamek 3 Dream Arena Block": 2238,
    "NBC Kamek 2 Left Room Bean Spot 1": 2239,
    "NBC Kamek 2 Left Room Bean Spot 2": 2240,
    "NBC East of Kamek 3 Bean Spot 1": 2241,
    "NBC East of Kamek 3 Bean Spot 2": 2242,
    "NBC Kamek 3 Western Bomb Room Bean Spot 1": 2243,
    "NBC Kamek 3 Western Bomb Room Bean Spot 2": 2244,
    "NBC Elevator to Flame Pipes Block 1": 2301,
    "NBC Elevator to Flame Pipes Block 2": 2302,
    "NBC Left Balcony Block": 2303,
    "NBC Bottom Left of Flame Pipes Block 1": 2304,
    "NBC Bottom Left of Flame Pipes Block 2": 2305,
    "NBC Bottom Right of Flame Pipes Block": 2306,
    "NBC Front Balcony Block 1": 2307,
    "NBC Front Balcony Block 2": 2308,
    "NBC Front Balcony Block 3": 2309,
    "DNBC Left Flame Pipe Dream Room 3 Block 1": 2310,
    "DNBC Left Flame Pipe Dream Room 3 Block 2": 2311,
    "DNBC Bottom Right Flame Pipe Dream Room 2 Block": 2312,
    "DNBC Top Right Flame Pipe Dream Room 1 Block 1": 2313,
    "DNBC Top Right Flame Pipe Dream Room 1 Block 2": 2314,
    "DNBC Top Right Flame Pipe Dream Room 1 Block 3": 2315,
    "NBC Left Balcony Bean Spot": 2316,
    "NBC Right Balcony Bean Spot 1": 2317,
    "NBC Right Balcony Bean Spot 2": 2318,
    "NBC Bottom Right of Flame Pipes Bean Spot 1": 2319,
    "NBC Bottom Right of Flame Pipes Bean Spot 2": 2320,
    "NBC Front Balcony Bean Spot 1": 2321,
    "NBC Front Balcony Bean Spot 2": 2322,
    "NBC Front Balcony Bean Spot 3": 2323,
    "NBC Front Balcony Bean Spot 4": 2324,
    "DNBC Bowser's Dream First Bowser Encounter Block": 2401,
    "DNBC Bowser's Dream Path Back 2 Block 1": 2402,
    "DNBC Bowser's Dream Path Back 2 Block 2": 2403,
    "DNBC Bowser's Dream Path Back 4 Block 1": 2404,
    "DNBC Bowser's Dream Path Back 4 Block 2": 2405,
    "DNBC Bowser's Dream Path Back 7 Block": 2406,
    "DNBC Bowser's Dream Door to Giant Cannons Block 1": 2407,
    "DNBC Bowser's Dream Door to Giant Cannons Block 2": 2408,
    "DNBC Bowser's Dream Giant Cannons Block": 2409,
}


# Each Location instance must correctly report the "game" it belongs to.
# To make this simple, it is common practice to subclass the basic Location class and override the "game" field.
class MLDTLocation(Location):
    game = "Mario and Luigi Dream Team"


# Let's make one more helper method before we begin actually creating locations.
# Later on in the code, we'll want specific subsections of LOCATION_NAME_TO_ID.
# To reduce the chance of copy-paste errors writing something like {"Chest": LOCATION_NAME_TO_ID["Chest"]},
# let's make a helper method that takes a list of location names and returns them as a dict with their IDs.
# Note: There is a minor typing quirk here. Some functions want location addresses to be an "int | None",
# so while our function here only ever returns dict[str, int], we annotate it as dict[str, int | None].
def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
    return {location_name: LOCATION_NAME_TO_ID[location_name] for location_name in location_names}


def create_all_locations(world: MLDTWorld) -> None:
    create_regular_locations(world)
    create_events(world)


def create_regular_locations(world: MLDTWorld) -> None:
    # Finally, we need to put the Locations ("checks") into their regions.
    # Once again, before we do anything, we can grab our regions we created by using world.get_region()
    blimport = world.get_region("Blimport")
    piillo_castle = world.get_region("Pi'illo Castle")
    piillo_castle_deep = world.get_region("Pi'illo Castle Dream's Deep")
    blimport_underground = world.get_region("Under Blimport Bridge")
    mushrise_park = world.get_region("Mushrise Park Main Area")
    mushrise_hammer = world.get_region("Mushrise Park Hammer Regions")
    past_gate = world.get_region("Dozing Sands/Driftwood Shore Outskirts")
    dozing_tracks = world.get_region("Dozing Sands Track Area")
    dozing_dreampoints = world.get_region("Dozing Sands Dreamstone Area")
    wakeport = world.get_region("Wakeport")
    wakeport_ultibed = world.get_region("Wakeport Ultibed")
    mount_pajamaja_entrance = world.get_region("Mount Pajamaja Before Base")
    mount_pajamaja_base = world.get_region("Mount Pajamaja Base")
    mount_pajamaja_middle = world.get_region("Mount Pajamaja Middle")
    mount_pajamaja_peak = world.get_region("Mount Pajamaja Peak")
    mount_pajamaja_dreampoint = world.get_region("Mount Pajamaja Summit Dreampoint")
    driftwood_shore = world.get_region("Driftwood Shore Dreampoint Area")
    driftwood_shore_egg = world.get_region("Driftwood Shore Dream Egg Dream")
    somnom_woods = world.get_region("Somnom Woods Before Tracks")
    somnom_woods_tracks = world.get_region("Somnom Woods Track Area")
    somnom_woods_post_tracks = world.get_region("Somnom Woods After Tracks")
    neo_castle = world.get_region("Neo Bowser Castle Before First Progressive Spin")
    neo_castle_spin = world.get_region("Neo Bowser Castle After First Porgressive Spin")
    neo_castle_flame = world.get_region("Neo Bowser Castle Flame Pipe Area")
    neo_castle_dream = world.get_region("Neo Bowser Castle Bowser's Dream")

    locations_to_add = [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
                        {}, {}, {}, {}, {}, {}, {}, {}, {}]
    
    for l in LOCATION_NAME_TO_ID:
        i = LOCATION_NAME_TO_ID[l]
        locations_to_add[i // 100][l] = i

    blimport.add_locations(locations_to_add[0], MLDTLocation)
    piillo_castle.add_locations(locations_to_add[1], MLDTLocation)
    piillo_castle_deep.add_locations(locations_to_add[2], MLDTLocation)
    blimport_underground.add_locations(locations_to_add[3], MLDTLocation)
    mushrise_park.add_locations(locations_to_add[4], MLDTLocation)
    mushrise_hammer.add_locations(locations_to_add[5], MLDTLocation)
    past_gate.add_locations(locations_to_add[6], MLDTLocation)
    dozing_tracks.add_locations(locations_to_add[7], MLDTLocation)
    dozing_dreampoints.add_locations(locations_to_add[8], MLDTLocation)
    wakeport.add_locations(locations_to_add[9], MLDTLocation)
    wakeport_ultibed.add_locations(locations_to_add[10], MLDTLocation)
    mount_pajamaja_entrance.add_locations(locations_to_add[11], MLDTLocation)
    mount_pajamaja_base.add_locations(locations_to_add[12], MLDTLocation)
    mount_pajamaja_middle.add_locations(locations_to_add[13], MLDTLocation)
    mount_pajamaja_peak.add_locations(locations_to_add[14], MLDTLocation)
    mount_pajamaja_dreampoint.add_locations(locations_to_add[15], MLDTLocation)
    driftwood_shore.add_locations(locations_to_add[16], MLDTLocation)
    driftwood_shore_egg.add_locations(locations_to_add[17], MLDTLocation)
    somnom_woods.add_locations(locations_to_add[18], MLDTLocation)
    somnom_woods_tracks.add_locations(locations_to_add[19], MLDTLocation)
    somnom_woods_post_tracks.add_locations(locations_to_add[20], MLDTLocation)
    neo_castle.add_locations(locations_to_add[21], MLDTLocation)
    neo_castle_spin.add_locations(locations_to_add[22], MLDTLocation)
    neo_castle_flame.add_locations(locations_to_add[23], MLDTLocation)
    neo_castle_dream.add_locations(locations_to_add[24], MLDTLocation)


    # One way to create locations is by just creating them directly via their constructor.
    #bottom_left_chest = MLDTLocation(
    #    world.player, "Bottom Left Chest", world.location_name_to_id["Bottom Left Chest"], overworld
    #)

    # You can then add them to the region.
    #overworld.locations.append(bottom_left_chest)

    # A simpler way to do this is by using the region.add_locations helper.
    # For this, you need to have a dict of location names to their IDs (i.e. a subset of location_name_to_id)
    # Aha! So that's why we made that "get_location_names_with_ids" helper method earlier.
    # You also need to pass your overridden Location class.
    #bottom_right_room_locations = get_location_names_with_ids(
    #    ["Bottom Right Room Left Chest", "Bottom Right Room Right Chest"]
    #)
    #bottom_right_room.add_locations(bottom_right_room_locations, MLDTLocation)

    #top_left_room_locations = get_location_names_with_ids(["Top Left Room Chest"])
    #top_left_room.add_locations(top_left_room_locations, MLDTLocation)

    #right_room_locations = get_location_names_with_ids(["Right Room Enemy Drop"])
    #right_room.add_locations(right_room_locations, MLDTLocation)

    # Locations may be in different regions depending on the player's options.
    # In our case, the hammer option puts the Top Middle Chest into its own room called Top Middle Room.
    #top_middle_room_locations = get_location_names_with_ids(["Top Middle Chest"])
    #if world.options.hammer:
    #    top_middle_room = world.get_region("Top Middle Room")
    #    top_middle_room.add_locations(top_middle_room_locations, MLDTLocation)
    #else:
    #    overworld.add_locations(top_middle_room_locations, MLDTLocation)

    # Locations may exist only if the player enables certain options.
    # In our case, the extra_starting_chest option adds the Bottom Left Extra Chest location.
    #if world.options.extra_starting_chest:
        # Once again, it is important to stress that even though the Bottom Left Extra Chest location doesn't always
        # exist, it must still always be present in the world's location_name_to_id.
        # Whether the location actually exists in the seed is purely determined by whether we create and add it here.
    #    bottom_left_extra_chest = get_location_names_with_ids(["Bottom Left Extra Chest"])
    #    overworld.add_locations(bottom_left_extra_chest, MLDTLocation)


def create_events(world: MLDTWorld) -> None:
    # Sometimes, the player may perform in-game actions that allow them to progress which are not related to Items.
    # In our case, the player must press a button in the top left room to open the final boss door.
    # AP has something for this purpose: "Event locations" and "Event items".
    # An event location is no different than a regular location, except it has the address "None".
    # It is treated during generation like any other location, but then it is discarded.
    # This location cannot be "sent" and its item cannot be "received", but the item can be used in logic rules.
    # Since we are creating more locations and adding them to regions, we need to grab those regions again first.
    blimport = world.get_region("Blimport")
    piillo_castle = world.get_region("Pi'illo Castle")
    piillo_castle_deep = world.get_region("Pi'illo Castle Dream's Deep")
    blimport_underground = world.get_region("Under Blimport Bridge")
    mushrise_park = world.get_region("Mushrise Park Main Area")
    mushrise_hammer = world.get_region("Mushrise Park Hammer Regions")
    past_gate = world.get_region("Dozing Sands/Driftwood Shore Outskirts")
    dozing_tracks = world.get_region("Dozing Sands Track Area")
    dozing_dreampoints = world.get_region("Dozing Sands Dreamstone Area")
    wakeport = world.get_region("Wakeport")
    wakeport_ultibed = world.get_region("Wakeport Ultibed")
    mount_pajamaja_entrance = world.get_region("Mount Pajamaja Before Base")
    mount_pajamaja_base = world.get_region("Mount Pajamaja Base")
    mount_pajamaja_middle = world.get_region("Mount Pajamaja Middle")
    mount_pajamaja_peak = world.get_region("Mount Pajamaja Peak")
    mount_pajamaja_dreampoint = world.get_region("Mount Pajamaja Summit Dreampoint")
    driftwood_shore = world.get_region("Driftwood Shore Dreampoint Area")
    driftwood_shore_egg = world.get_region("Driftwood Shore Dream Egg Dream")
    somnom_woods = world.get_region("Somnom Woods Before Tracks")
    somnom_woods_tracks = world.get_region("Somnom Woods Track Area")
    somnom_woods_post_tracks = world.get_region("Somnom Woods After Tracks")
    neo_castle = world.get_region("Neo Bowser Castle Before First Progressive Spin")
    neo_castle_spin = world.get_region("Neo Bowser Castle After First Porgressive Spin")
    neo_castle_flame = world.get_region("Neo Bowser Castle Flame Pipe Area")
    neo_castle_dream = world.get_region("Neo Bowser Castle Bowser's Dream")

    # One way to create an event is simply to use one of the normal methods of creating a location.
    #button_in_top_left_room = MLDTLocation(world.player, "Top Left Room Button", None, top_left_room)
    #top_left_room.locations.append(button_in_top_left_room)

    # We then need to put an event item onto the location.
    # An event item is an item whose code is "None" (same as the event location's address),
    # and whose classification is "progression". Item creation will be discussed more in items.py.
    # Note: Usually, items are created in world.create_items(), which for us happens in items.py.
    # However, when the location of an item is known ahead of time (as is the case with an event location/item pair),
    # it is common practice to create the item when creating the location.
    # Since locations also have to be finalized after world.create_regions(), which runs before world.create_items(),
    # we'll create both the event location and the event item in our locations.py code.
    #button_item = items.APQuestItem("Top Left Room Button Pressed", ItemClassification.progression, None, world.player)
    #button_in_top_left_room.place_locked_item(button_item)

    # A way simpler way to do create an event location/item pair is by using the region.create_event helper.
    # Luckily, we have another event we want to create: The Victory event.
    # We will use this event to track whether the player can win the game.
    # The Victory event is a completely optional abstraction - This will be discussed more in set_rules().
    #final_boss_room.add_event(
    #    "Final Boss Defeated", "Victory", location_type=MLDTLocation, item_type=items.APQuestItem
    #)
    neo_castle_dream.add_event(
        "Dreamy Bowser Defeated", "Victory", location_type=MLDTLocation, item_type=items.MLDTItem
    )

    # If you create all your regions and locations line-by-line like this,
    # the length of your create_regions might get out of hand.
    # Many worlds use more data-driven approaches using dataclasses or NamedTuples.
    # However, it is worth understanding how the actual creation of regions and locations works,
    # That way, we're not just mindlessly copy-pasting! :)
